site_name: timetravelCat's profile and tech docs
theme:
  name: dracula
  features:
    - navigation.tabs
    - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
