### Site metadata ###

site_name: timetravelCat's profile and tech docs
site_description: A profile and tech docs site for timetravelCat
site_url: https://timetravelCat.github.io/profile/
repo_url: https://github.com/timetravelCat/profile

### Build settings ###

theme:
    name: dracula
    
plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
